// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Break break
//
// swagger:model Break
type Break struct {

	// end timestamp
	EndTimestamp int64 `json:"endTimestamp,omitempty"`

	// position lat
	PositionLat float32 `json:"positionLat,omitempty"`

	// position long
	PositionLong float32 `json:"positionLong,omitempty"`

	// start timestamp
	StartTimestamp int64 `json:"startTimestamp,omitempty"`
}

// Validate validates this break
func (m *Break) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this break based on context it is used
func (m *Break) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Break) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Break) UnmarshalBinary(b []byte) error {
	var res Break
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
